//Reference Link: https://github.com/aarad-ac/EFCore
//Reference Link: https://github.com/aarad-ac/AzureStorageAndMigrations
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Lab4.Models
{
    public class Community
    {
        /**
         * i.	string Id
                1.	make sure this is not database generated by setting the DatabaseGenerated attribute to DatabaseGeneratedOption.None
                2.	Display name should read ‘Registration Number’
                3.	Add the ‘Required’ attribute
         */
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Registration Number")]
        [Required]
        public string ID { get; set; }

        public ICollection<CommunityMembership> Membership
        {    get;   set;    }
        /**
         * ii.	string Title
                1.	Add the ‘Required’ attribute
                2.	Add the ‘StringLength’ attribute, with a value of max 50 and MinimumLength = 3

         */
        [StringLength(50, MinimumLength = 3)]
        [Required]
        public string title { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "money")]
        public decimal Budget { get; set; }
        
    }
}
